FROM python:3.9-slim

WORKDIR /app

RUN echo "[global]\n\
timeout = 60\n\
index-url = https://pypi.tuna.tsinghua.edu.cn/simple\n\
extra-index-url = https://mirrors.aliyun.com/pypi/simple/\n\
trusted-host = pypi.tuna.tsinghua.edu.cn\n\
              mirrors.aliyun.com" > /etc/pip.conf

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY generate_data.py .

CMD ["python", "generate_data.py"]