FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY pipeline/ ./pipeline/

CMD bash -c "\
    python pipeline/stage_layer/extractor.py & \
    python pipeline/processing/streaming/kafka-ch.py & \
    wait"
