FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY pipeline/ ./pipeline/

CMD bash -c "\
    python -u /app/pipeline/stage_layer/extractor.py & \
    python -u /app/pipeline/processing/streaming/producer.py & \
    python -u /app/pipeline/processing/streaming/consumer.py & \
    python -u /app/pipeline/processing/clickhouse_views/views.py & \
    wait"
