{
 "title": "Sales Dashboard",
 "refresh": "10s",
 "panels": [
  {
   "title": "Sales Over Time",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 24, "h": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "query": "SELECT sale_day AS t, total_revenue AS total_sales FROM daily_sales_summary ORDER BY t"
    }
   ]
  },
  {
   "title": "Top 10 Products",
   "type": "barchart",
   "gridPos": { "x": 0, "y": 9, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "query": "SELECT product_name, sumMerge(revenue_state) AS total_sales FROM top_products GROUP BY product_name ORDER BY total_sales DESC LIMIT 10"
    }
   ]
  },
  {
   "title": "Average Check by Seller",
   "type": "barchart",
   "gridPos": { "x": 12, "y": 9, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "query": "SELECT seller_full_name, avgMerge(avg_check_state) AS avg_check FROM avg_check_by_seller GROUP BY seller_full_name ORDER BY avg_check DESC LIMIT 10"
    }
   ]
  },
  {
   "title": "Revenue by Product Category",
   "type": "barchart",
   "gridPos": { "x": 0, "y": 17, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "query": "SELECT product_category, sumMerge(total_revenue_state) AS total_revenue FROM revenue_by_category GROUP BY product_category ORDER BY total_revenue DESC"
    }
   ]
  },
  {
   "title": "Hourly Sales Activity (Last 7 Days)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 17, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "SELECT sale_hour AS t, sale_count, revenue FROM hourly_sales_activity ORDER BY t"
    }
   ]
  }
 ]
}