groups:
  - name: clickhouse-alerts
    rules:
      - alert: ClickhouseDown
        expr: up{job="clickhouse"} == 0
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "ClickHouse instance is down"

      - alert: ClickhouseHighQueryLatency
        expr: rate(clickhouse_http_request_duration_seconds_sum[5m]) / rate(clickhouse_http_request_duration_seconds_count[5m]) > 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High ClickHouse HTTP query latency"
